# Generated by Django 6.0.5 on 2026-06-20 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('custom', 'Custom SMTP')], default='gmail', max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255)),
                ('encrypted_password', models.TextField(help_text='Encrypted SMTP/app password')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal campaign name', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use {name}, or start with "Hi," and the system will add the name.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Queued', 'Queued'), ('Sending', 'Sending'), ('Completed', 'Completed'), ('Paused', 'Paused'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.emailaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Valued Client', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Sending', 'Sending'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Replied', 'Replied'), ('Bounced', 'Bounced'), ('Unsubscribed', 'Unsubscribed'), ('Skipped', 'Skipped')], default='Pending', max_length=20)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('reply_text', models.TextField(blank=True, null=True)),
                ('sent_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('campaign', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SuppressionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('manual', 'Manual block')], default='unsubscribed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppression_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email')},
            },
        ),
    ]
