# Generated by Django 6.0.5 on 2026-06-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(default='CampaignManager helps you send secure, hyper-personalized cold emails using your own Gmail accounts.', max_length=300)),
                ('contact_email', models.EmailField(default='support@campaignmanager.com', max_length=254)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('copyright_year', models.CharField(default='2026', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
