# Generated by Django 6.0.5 on 2026-06-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='column_1_title',
            field=models.CharField(default='Platform', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='column_2_title',
            field=models.CharField(default='Resources', max_length=50),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2')], default=1)),
                ('name', models.CharField(help_text='Text displayed on the website', max_length=50)),
                ('url', models.CharField(help_text="Use '/dashboard/' for internal links or 'https://...' for external", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='footer.footersettings')),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
    ]
