# Generated by Django 6.0.5 on 2026-06-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_footersettings_column_1_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Privacy Policy', max_length=100)),
                ('slug', models.SlugField(help_text='e.g., privacy, terms', unique=True)),
                ('content', models.TextField(help_text='Write your content here. Paragraphs will be formatted automatically.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
            },
        ),
    ]
