# Generated by Django 6.0.5 on 2026-06-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_legalpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Cold Email Guide', max_length=150)),
                ('slug', models.SlugField(help_text='e.g., cold-email-guide', unique=True)),
                ('content', models.TextField(help_text='Write your guide here. You can use basic HTML tags like <b>, <h3>, or <ul> if you want!')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource Page',
                'verbose_name_plural': 'Resource Pages',
            },
        ),
    ]
