# Generated by Django 6.0.5 on 2026-06-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_resourcepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Platform, Resources, Company', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first (left to right)')),
            ],
            options={
                'verbose_name_plural': '2. Footer Columns (Main Categories)',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name_plural': '1. Global Footer Settings'},
        ),
        migrations.AlterModelOptions(
            name='legalpage',
            options={'verbose_name': 'Legal Page', 'verbose_name_plural': '3. Legal Pages'},
        ),
        migrations.AlterModelOptions(
            name='resourcepage',
            options={'verbose_name': 'Resource Page', 'verbose_name_plural': '4. Resource Pages'},
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='column_1_title',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='column_2_title',
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_text',
            field=models.TextField(default='CampaignManager is a secure, intelligent outreach platform.', max_length=300),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='support@campaignmanager.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='content',
            field=models.TextField(help_text='Write your guide here. HTML tags supported.'),
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Text displayed on website', max_length=50)),
                ('url', models.CharField(help_text='e.g., /dashboard/ or https://google.com', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='footer.footercolumn')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
